### ISSUE TITLE
Did 4.0.0 get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [sferik/t-ruby#469]
👋 looks like the tarball checksum for 4.0.0 release got changed, raise this issue to confirm if there was re-tagging. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/169478

**Comment by sferik** [comment]
Hey, I just left a comment on the Homebrew issue. I don't remember retagging this but it was a year ago, so I suppose it's possible. I might just release a new version if that would solve the problem.

**Comment by sferik** [comment]
I just pushed a new gem release (version 4.1.1).

**Comment by chenrui333** [comment]
@sferik thanks for the new release, that helps. Closing the issue now.
